parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
env:
  browser: true
  es6: true
  worker: true
plugins:
  - simple-import-sort
  - "@typescript-eslint"
extends:
  - standard
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  array-bracket-spacing:
    - warn
    - never
  comma-dangle:
    - warn
    - always-multiline
  indent:
    - warn
    - tab
    - SwitchCase: 1
  no-tabs: 0
  multiline-ternary: 0
  semi:
    - warn
    - always
  space-before-function-paren: 0
  spaced-comment: 0
  simple-import-sort/imports:
    - warn
    - groups:
        - [ "^@?\\w" ]
        - [ "^" ]
        - [ "^\\." ]
        - [ "^\\u0000" ]
  simple-import-sort/exports:
    - warn
  "@typescript-eslint/ban-ts-comment": 0
  "@typescript-eslint/ban-ts-ignore": 0
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/explicit-member-accessibility": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/explicit-module-boundary-types":
    - warn
  # https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-use-before-define.md#how-to-use
  no-use-before-define: 0
  "@typescript-eslint/no-use-before-define":
    - warn
