name = "claws"
usage_model = "bundled"

compatibility_date = "2023-09-16"
compatibility_flags = []

workers_dev = false
account_id = "<ACCOUNT_ID>"

route = { pattern = "claws.<DOMAIN>/*", zone_name = "<DOMAIN>" }
